import React, { useEffect, useMemo, useState } from 'react';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import { ocrAPI } from '../services/api';

const GROUPS = [['Beneficiary details', ['beneficiaryId','childName','dateOfBirth','age','gender','parentName','parentId','phone','address','anganwadiId']], ['Health and growth', ['height','weight','muac','nutritionalStatus','screeningDate','healthObservations']], ['Nutrition', ['nutritionDetails']], ['Vaccination', ['vaccineName','dose','vaccinationDate','nextVaccinationDate','vaccinationStatus']]];
const LABELS = { beneficiaryId:'Beneficiary ID',childName:'Child name',dateOfBirth:'Date of birth',age:'Age',gender:'Gender',parentName:'Parent / guardian',parentId:'Parent / guardian ID',phone:'Phone number',address:'Address',anganwadiId:'Anganwadi Centre ID',height:'Height',weight:'Weight',muac:'MUAC',nutritionalStatus:'Nutritional status',screeningDate:'Screening date',healthObservations:'Health observations',nutritionDetails:'Nutrition information',vaccineName:'Vaccine name',dose:'Dose',vaccinationDate:'Vaccination date',nextVaccinationDate:'Next vaccination date',vaccinationStatus:'Vaccination status' };

export default function OCRWorkflow() {
  const [file,setFile]=useState(null),[result,setResult]=useState(null),[fields,setFields]=useState({}),[history,setHistory]=useState([]),[status,setStatus]=useState(''),[error,setError]=useState(''),[module,setModule]=useState('document'),[saving,setSaving]=useState(false),[verified,setVerified]=useState(false);
  const preview=useMemo(()=>file?URL.createObjectURL(file):'', [file]);
  const load=async()=>{try{setHistory((await ocrAPI.getLatest(20)).documents||[])}catch{}};
  useEffect(()=>{load();return()=>{if(preview)URL.revokeObjectURL(preview)}},[preview]);
  const choose=e=>{setFile(e.target.files?.[0]||null);setResult(null);setFields({});setVerified(false);setError('');setStatus('')};
  const process=async()=>{if(!file)return setError('Choose a JPG, PNG, PDF, or text document first.');setError('');setVerified(false);setModule('document');setStatus('Processing document…');try{const r=await ocrAPI.processDocument(file);setResult(r.data);setFields(r.data.structured?.fields||{});setStatus('Ready for review');load()}catch(e){setError(e.message||'OCR processing failed. Try a clearer document.');setStatus('OCR processing failed')}};
  const open=async id=>{try{const r=await ocrAPI.getById(id);setResult(r.document);setFields(r.document.structured?.fields||r.document.analysis?.structured?.fields||{});setVerified(false);setModule('document');setStatus('Ready for review')}catch(e){setError(e.message)}};
  const removeHistory=async id=>{if(!window.confirm('Delete this OCR history item and its stored original document?'))return;try{await ocrAPI.delete(id);setHistory(items=>items.filter(item=>item._id!==id));if(result?.ocrDocumentId===id){setResult(null);setFields({});setStatus('')}}catch(e){setError(e.message||'Could not delete this OCR history item.')}};
  const save=async()=>{if(!verified)return setError('Please confirm that you verified the extracted information against the original document.');setSaving(true);setError('');setStatus('Validating fields…');try{await ocrAPI.save(result.ocrDocumentId,module,fields,true);setStatus('Saved successfully');load()}catch(e){setError(e.message||'Could not save verified data.');setStatus('Needs review')}finally{setSaving(false)}};
  const extracted=Object.values(fields).filter(Boolean).length,missing=Object.values(fields).filter(v=>!v).length;
  return <div className="page"><Navbar/><div className="page-content"><Sidebar role="worker"/><main className="main-content"><h2>Smart OCR</h2><p>Upload, review against the original document, and save only verified information to PoshanAI.</p>
    <div className="form-container"><h3>1. Upload document</h3><div className="form-group"><label htmlFor="ocr-document">JPG, JPEG, PNG, PDF, or TXT (max 10 MB)</label><input id="ocr-document" type="file" accept=".jpg,.jpeg,.png,.pdf,.txt,image/jpeg,image/png,application/pdf,text/plain" onChange={choose}/></div>{file&&<div className="warning-message">{file.name} · {(file.size/1024).toFixed(1)} KB <button type="button" className="link-button" onClick={()=>setFile(null)}>Remove</button></div>}<button className="submit-btn" type="button" disabled={!file||status.includes('…')} onClick={process}>Process document</button>{status&&<p><strong>Status:</strong> {status}</p>}{error&&<div className="error-message">{error}</div>}</div>
    {result&&<div className="ocr-review-grid"><section className="form-container"><h3>2. Original document</h3>{file?.type==='application/pdf'||result.source_mime_type==='application/pdf'?<iframe title="Original document" src={file?preview:ocrAPI.fileUrl(result.ocrDocumentId)} style={{width:'100%',minHeight:520,border:0}}/>:file?<img src={preview} alt="Uploaded original" style={{maxWidth:'100%',maxHeight:560}}/>:<p>Original document is stored privately.</p>}</section><section className="form-container"><h3>3. Review extracted information</h3><p><strong>Document type:</strong> {result.documentType||'Other/Unknown'}</p><p><strong>Classification confidence:</strong> {result.classification?.confidence?`${result.classification.confidence}%`:'Document type requires review'}</p><p><strong>Extracted:</strong> {extracted} &nbsp; <strong>Missing:</strong> {missing}</p>{result.validationWarnings?.length>0&&<div className="warning-message">{result.validationWarnings.join(' ')}</div>}{GROUPS.map(([title,keys])=><section className="ocr-section" key={title}><h4>{title}</h4>{keys.map(k=><div className={`form-group ${fields[k]?'ocr-field-review':'ocr-field-missing'}`} key={k}><label htmlFor={`ocr-${k}`}>{LABELS[k]} <small>{fields[k]?'Review recommended':'Not found in document'}</small></label><input id={`ocr-${k}`} value={fields[k]||''} placeholder="Not found in document" onChange={e=>setFields(c=>({...c,[k]:e.target.value}))}/></div>)}</section>)}<details className="ocr-raw-text"><summary>Review raw extracted text</summary><pre>{result.rawText||''}</pre></details><h4>4. Save to existing module</h4><p>Choose a clinical module only when the document contains a matching beneficiary ID. Otherwise submit it as a verified OCR report.</p><select value={module} onChange={e=>setModule(e.target.value)}><option value="health">Health / growth</option><option value="nutrition">Nutrition</option><option value="vaccination">Vaccination</option><option value="document">Verified OCR report</option></select><div className="ocr-verification-check" style={{display:'block',marginTop:'16px',marginBottom:'12px'}}><label><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> I verified every extracted value against the original document.</label></div><button className="submit-btn" type="button" disabled={saving||!verified} onClick={save}>{saving?'Submitting…':module==='document'?'Submit verified report':'Verify and save'}</button></section></div>}
    <div className="form-container"><h3>OCR history</h3>{history.length?<ul>{history.map(x=><li key={x._id}><button type="button" className="link-button" onClick={()=>open(x._id)}>{x.original_filename}</button> — {x.document_type||'Unknown'} — {x.review_status||'pending'} — {new Date(x.createdAt).toLocaleString()} <button type="button" className="link-button" onClick={()=>removeHistory(x._id)} aria-label={'Delete '+x.original_filename}>Clear</button></li>)}</ul>:<p>No OCR documents processed yet.</p>}</div></main></div></div>;
}
